### ISSUE TITLE
Vocabulary for completeness of taxon indexing

### ISSUE THREAD

**Issue by larsgw** [identification-resources/catalog#94]
A major bottleneck for adding taxon indices to keys is that they are expected to be complete. Allowing partial resources (with proper indication of their completeness) removes this bottleneck.

```yml
levels:
  - ...
status:
  all_taxa: false # not all taxa included
  all_taxa_authorship: false # not all taxa with authorship included
  all_synonyms: false # not all synonyms included
```

The first/last/any key (decide) can also have `all_resources: false` to indicate not all resources are included.
